config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :discussions
  resources :posts
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
                        # splits off comments into seperate module - posts/comments_controller
    resources :comments, module: :posts
  end

  resources :discussions do
    resources :comments, module: :discussions
  end  

  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  has_many :comments, as: :commentable
end

app/controllers/discussions/comments_controller.rb
class Discussions::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Discussion.find(params[:discussion_id])
  end
  
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if discussion.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', discussion, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if discussion.persisted? %>
      <%= link_to "Cancel", discussion, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", discussions_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit Discussion</h1>

<%= render 'form', discussion: @discussion %>

app/views/discussions/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Discussions</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_discussion_path, class: 'btn btn-primary' do %>
    Add New Discussion
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @discussions.each do |discussion| %>
        <%= content_tag :tr, id: dom_id(discussion), class: dom_class(discussion) do %>
          

                      <td><%= discussion.title %></td>
          
          
            <td><%= link_to 'Show', discussion %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form', discussion: @discussion %>

app/views/discussions/show.html.erb
<div class="page-header">
  <%= link_to discussions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Discussions
  <% end %>
  <%= link_to edit_discussion_path(@discussion), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show discussion</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @discussion.title %></dd>

</dl>


<h2>Comments</h2>

<div id="comments">
  <%= render partial: "comments/form", 
             locals: { commentable: @discussion } %>
  <%= render @discussion.comments.where(parent_id: nil), max_nesting: 5 %>
</div>